### PR TITLE
Release 0.1.2

### PR DESCRIPTION
**Pull request by TimoKramer**

### CODE REVIEW

**Comment by TimoKramer** [comment]
@kordano Are you able to review this PR or should I request someone else?

**Comment by kordano** [comment]
I can review it.

**Comment by TimoKramer** [comment]
How do I get a dated version from clojars for the deploy?

**Comment by kordano** [comment]
What do you mean by "dated version"?

**Comment by TimoKramer** [comment]
it says it can not build because of a snapshot-dependency. use a dated version.

it seems to be something with a date at the end instead of SNAPSHOT i suppose.

**Comment by TimoKramer** [comment]
```
Release versions may not depend upon snapshots. 
Freeze snapshots to dated versions or set the LEIN_SNAPSHOTS_IN_RELEASE environment variable to override.
```
maybe we stick with a snapshot for now? Or should I ask alex to release a non-SNAPSHOT version?

**Comment by jsmassa** [comment]
Should we change the process for this repo to automatic releases as well, so we don't have to do these merges anymore?

**Pull request closed without merging**
