### PR TITLE
Bump versions.

### LINKED ISSUE #14: Use replikativ/konserve-jdbc to enable synchronous execution

### PR DESCRIPTION
**Pull request by whilo**
Closes #14

### CODE REVIEW

**Review by jsmassa — COMMENTED** [review]
Looks good to me. One of the integration tests needs fixing though.

**Comment by whilo** [comment]
For some reason the MariaDB container invokes `pwgen` and does not find that anymore. I had pinged @TimoKramer, maybe he has an idea.

**Comment by TimoKramer** [comment]
> For some reason the MariaDB container invokes `pwgen` and does not find that anymore. I had pinged @TimoKramer, maybe he has an idea.

I don't know what's going on with the pipe. The image is clearly changed away from circleci's cimg-image of postgres and mariadb to the official ones and still it builds with the cimg-images. It seems to be a caching issue. CircleCI seems to degrade rapidly... :(

**Comment by TimoKramer** [comment]
It works if I run the tests locally so just merge???

**Comment by jsmassa** [comment]
In that case, we can merge. 

We should solve the container issue anyway. Couldn't we just use the images we are using in konserve-jdbc?

**Comment by TimoKramer** [comment]
> In that case, we can merge.
> 
> We should solve the container issue anyway. Couldn't we just use the images we are using in konserve-jdbc?

sure, that would be good. maybe update the images to a newer version.

**Comment by jsmassa** [comment]
I created #18 for the Pipeline issue

**Pull request merged**
